sonar.projectKey=red-frontend
sonar.projectName=Red Project Frontend
sonar.projectVersion=1.0

# Source code
sonar.sources=src

# Exclusions (VERY important for speed)
sonar.exclusions=node_modules/**,build/**,dist/**,public/**

# Encoding
sonar.sourceEncoding=UTF-8

# SonarQube server
sonar.host.url=http://host.docker.internal:9000

# Auth
sonar.token=sqp_f6645db90ee83c601b4d1f005663ac8c4d2f8b45